language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ak1738/docker-react-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true ak1738/docker-react-workflow npm run test -- --coverage