language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ak1738/docker-react-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true ak1738/docker-react-workflow npm run test -- --coverage

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-workflow"
  env: "Dockerreactworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-002394450353"
  bucket_path: "docker-react-workflow"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
